import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Evencha',
  description: 'Generated by Evencha',
  authors: [
    {
      name: 'gonzaemon111',
      url: 'https://gonzaemon.dev',
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body>{children}</body>
    </html>
  );
}
